name: Build OpenMarketplace ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, curl, dom, zip, pdo, pdo_mysql, opcache
          tools: composer:v2

      # Install dependencies but DO NOT run scripts or plugins (prevents Symfony auto-scripts)
      - name: Install dependencies (no dev, no scripts/plugins)
        env:
          COMPOSER_MEMORY_LIMIT: -1
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSER_NO_PLUGINS: 1
        run: composer install --no-dev -o --prefer-dist --no-progress --no-scripts --ignore-platform-reqs

      # Create the ZIP in the CURRENT directory (no ../)
      - name: Make release ZIP (includes vendor/)
        run: |
          zip -r open-marketplace-built.zip . \
            -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-marketplace-built
          path: open-marketplace-built.zip
          if-no-files-found: error
